#logo: /assets/img/headshot_circle.png
title: Shreya's homepage
# description: >- # this means to ignore newlines until "baseurl:"

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: saujasv
github_username:  saujasv

# Build settings
remote_theme: mmistakes/minimal-mistakes@4.24.0
plugins:
  - jekyll-include-cache

author:
  name             : "Saujas Vaduguru"
  avatar           : "/assets/images/profilepicture.jpg"
  bio              : "PhD student at CMU LTI"
  location         : "Pittsburgh, PA, USA"
  github           : "saujasv"
  links:
    - label: "svadugur [A] cs [D] cmu [D] edu"
      icon: "fas fa-fw fa-envelope-square"
      url: ""
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/saujasv"
    - label: "  Google Scholar"
      icon: "ai ai-google-scholar-square"
      url: "https://scholar.google.com/citations?user=U2MUXuMAAAAJ&hl=en"
    - label: "  Semantic Scholar"
      icon: "ai ai-semantic-scholar-square"
      url: "https://www.semanticscholar.org/author/Saujas-Vaduguru/2111868853"

description: Masters at CMU LTI
show_downloads: true
theme: jekyll-theme-minimal
